name: Prevent Render Sleep

on:
  schedule:
    - cron: "*/13 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App to keep it alive
        run: |
          curl -s https://klaxon-api.onrender.com/api/health > /dev/null
