name: Trigger Sync in Batches

on:
  schedule:
    # - cron: "15 21 * * *"  # Batch 0 (3:45 AM IST)
    # - cron: "25 21 * * *"  # Batch 1 (3:55 AM IST)
    # - cron: "35 21 * * *"  # Batch 2 (4:05 AM IST)
    - cron: "25 11 * * *"  # Batch 0 (4:55 PM IST)
    - cron: "0 11 * * *"   # Batch 1 (4:30 PM IST)
    - cron: "10 11 * * *"  # Batch 2 (4:40 PM IST)
  workflow_dispatch:       # Optional manual trigger

jobs:
  trigger-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Klaxon API trigger-sync
        run: |
          curl -s https://klaxon-api.onrender.com/api/trigger-sync > /dev/null
