name: Trigger Sync Daily

on:
  schedule:
    - cron: "30 21 * * *"  # 3:00 AM IST
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sync API
        run: |
          echo "Triggering sync..."
          response=$(curl -s -o response.txt -w "%{http_code}" -X POST https://klaxon-api.onrender.com/api/trigger-sync)
          cat response.txt
          if [ "$response" -ne 200 ]; then
            echo "❌ Sync failed with HTTP status $response"
            exit 1
          fi
          echo "✅ Sync triggered successfully."
